# Generated by Django 5.1.6 on 2025-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='问题')),
                ('option_a', models.CharField(max_length=100, verbose_name='选项 A')),
                ('option_b', models.CharField(max_length=100, verbose_name='选项 B')),
                ('option_c', models.CharField(max_length=100, verbose_name='选项 C')),
                ('option_d', models.CharField(max_length=100, verbose_name='选项 D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正确答案')),
            ],
        ),
    ]
