# Generated by Django 5.1.6 on 2025-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.CharField(default=1, max_length=50, verbose_name='试题ID'),
            preserve_default=False,
        ),
    ]
