# Generated by Django 5.1.6 on 2025-04-04 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_question_test_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('enter', 'Enter'), ('respond', 'Respond'), ('submit', 'Submit')], max_length=10)),
                ('item_id', models.IntegerField()),
                ('cursor_time', models.DurationField()),
                ('source', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('archive', 'Archive'), ('sprint', 'Sprint')], max_length=10)),
                ('user_answer', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
