# Generated by Django 5.1.6 on 2025-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_useraction_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='item_id',
        ),
        migrations.AddField(
            model_name='useraction',
            name='test_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='试卷ID'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='cursor_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
