# Generated by Django 5.1.6 on 2025-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_useraction_item_id_useraction_test_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor_time_seq', models.FloatField(null=True)),
                ('hour_seq', models.IntegerField(null=True)),
                ('minute_seq', models.IntegerField(null=True)),
                ('day_of_week_seq', models.IntegerField(null=True)),
                ('action_type_encoded_seq', models.IntegerField(null=True)),
                ('time_diff_seq', models.FloatField(null=True)),
                ('is_exit_seq', models.BooleanField(default=False)),
                ('user_behavior_length_seq', models.IntegerField(null=True)),
                ('source_encoded_seq', models.IntegerField(null=True)),
                ('user_answer_encoded_seq', models.IntegerField(null=True)),
            ],
        ),
    ]
