# Generated by Django 5.1.6 on 2025-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_useractivityfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityfeature',
            name='test_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='useractivityfeature',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
