# Generated by Django 5.2 on 2025-04-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_test_alter_question_options_question_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='试题ID'),
        ),
    ]
