# Generated by Django 5.2 on 2025-04-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_question_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='题目ID'),
        ),
    ]
